services:
  planner-dev:
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:5173"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped
