services:
  planner:
    build: .
    image: ghcr.io/wcervin/optimize.cards:latest
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://127.0.0.1:3000/health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped
